### ISSUE TITLE
Add some basic blog features

### ISSUE THREAD

**Issue by MiteshShah** [dharmit/dharmit.github.io#1]
* Disqus Comment
* Github Page Link at end of post for easy editing and send pull request.

**Comment by dharmit** [comment]
Hi Mitesh,

Thanks for stopping by. 

> Disqus Comment

I would rather prefer getting feedback/comments on [twitter](https://twitter.com/dharm1t)

> Github Page Link at end of post for easy editing and send pull request.

I will make sure to add link to the post on this repo so that someone might suggest a change or correct me if I am wrong. :)
